server:
  port: 8180
  max-http-header-size: 102400

spring:
  datasource:
    url: jdbc:mysql://121.37.39.206:3306/fileuploadsys?characterEncoding=utf-8
    username: fileuploadsys
    password: Zrx@20041009
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 100MB






